---
name: file-search
break: true
indent: 4
---

# Learn more about GatorGrader and its supported checks by visiting this web site:
# https://github.com/GatorEducator/gatorgrader

# Explanation:
# --> a check without an "--exact" runs a count for an entity as an "at least"
# --> checks below a file in a specified directory are for that specific file and directory
# --> checks that appear stand-alone are for an entire Git repository

# --> check the Python program
search/search/main.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "def word_search(" --count 1 --exact
    MatchFileFragment --fragment "def human_readable_boolean(" --count 1 --exact
    MatchFileFragment --fragment "def confirm_valid_file(" --count 1 --exact
    MatchFileFragment --fragment "if confirm_valid_file" --count 1
    CountMultipleLineComments --language Python --count 5
    CountSingleLineComments --language Python --count 10

# --> check the Python program
search/tests/test_search.py:
    ConfirmFileExists
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "test_" --count 5 --exact
    CountMultipleLineComments --language Python --count 3

# --> check the technical writing for various characteristics
writing/reflection.md:
    ConfirmFileExists
    CountFileWords --count 500
    CountMarkdownTags --tag "heading" --count 14
    CountMarkdownTags --tag "code_block" --count 5 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "not a valid file" --count 1 --exact

# --> check that the number of commits in the Git repository is beyond a threshold
CountCommits --count 5
